--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/BossAnnouncement
projects:
  BossAnnouncement:
    path: ""
    libs:
    - src: notacoderr/apibossbar/apibossbar
      version: ^0.0.2
...
